# action.yml
name: "CreatePackage"
description: "Publish and package a dotnet app"
inputs:
  project-name: # id of input
    description: "Name of the project to make a package of"
    required: true
    default: "release"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.project-name }}
